version: "3"
services:
  web_app:
    container_name: "my_web_app"
    build: ./frontend
    ports:
      - "3000:80"
  node_app:
    container_name: "my_node_app"
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      MONGO_CONNECTION_STRING: mongodb://localhost:27017
  db:
    container_name: "mongo_db"
    image: mongo:3
    ports:
      - "27017:27017"
  db_sql:
    container_name: "mysql_db"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
volumes:
  mysql_data:
